#pragma once
#include <common.hpp>

#define BOOTROM_SIZE 512
#define ROM_STR00 0x0000
#define ROM_END00 ROM_STR00 + 16 KiB - 1
#define ROM_STRNN ROM_END00 + 1
#define ROM_ENDNN ROM_STRNN + 16 KiB - 1
#define ROM_RNG00 ROM_STR00 ... ROM_END00
#define ROM_RNGNN ROM_STRNN ... ROM_ENDNN
#define VRAM_START ROM_ENDNN + 1
#define VRAM_END VRAM_START + 8 KiB - 1
#define VRAM_RANGE VRAM_START ... VRAM_END
#define EXTRAM_START VRAM_END + 1
#define EXTRAM_END EXTRAM_START + 8 KiB - 1
#define EXTRAM_RANGE EXTRAM_START ... EXTRAM_END
#define WRAM_STR00 EXTRAM_END + 1
#define WRAM_END00 WRAM_STR00 + 4 KiB - 1
#define WRAM_STRNN WRAM_END00 + 1
#define WRAM_ENDNN WRAM_STRNN + 4 KiB - 1
#define WRAM_RNG00 WRAM_STR00 ... WRAM_END00
#define WRAM_RNGNN WRAM_STRNN ... WRAM_ENDNN
#define OAM_START WRAM_ENDNN + 1
#define OAM_END OAM_START + 0x9F
#define OAM_RANGE OAM_START ... OAM_END
#define UNUSABLE_START OAM_END + 1
#define UNUSABLE_END UNUSABLE_START + 0x5F
#define UNUSABLE_RANGE UNUSABLE_START ... UNUSABLE_END
#define IO_START UNUSABLE_END + 1
#define IO_END IO_START + 0x7F
#define IO_RANGE IO_START ... IO_END
#define HRAM_START IO_END + 1
#define HRAM_END HRAM_START + 0x7E
#define HRAM_RANGE HRAM_START ... HRAM_END
